// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.5.1
// source: msgqpb/msgq.proto

package msgq

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Ping struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ack bool `protobuf:"varint,1,opt,name=ack,proto3" json:"ack,omitempty"`
}

func (x *Ping) Reset() {
	*x = Ping{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgqpb_msgq_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_msgqpb_msgq_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_msgqpb_msgq_proto_rawDescGZIP(), []int{0}
}

func (x *Ping) GetAck() bool {
	if x != nil {
		return x.Ack
	}
	return false
}

type PingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ping *Ping `protobuf:"bytes,1,opt,name=ping,proto3" json:"ping,omitempty"`
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgqpb_msgq_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_msgqpb_msgq_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_msgqpb_msgq_proto_rawDescGZIP(), []int{1}
}

func (x *PingRequest) GetPing() *Ping {
	if x != nil {
		return x.Ping
	}
	return nil
}

type PingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pong *Ping `protobuf:"bytes,1,opt,name=pong,proto3" json:"pong,omitempty"`
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgqpb_msgq_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_msgqpb_msgq_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_msgqpb_msgq_proto_rawDescGZIP(), []int{2}
}

func (x *PingResponse) GetPong() *Ping {
	if x != nil {
		return x.Pong
	}
	return nil
}

type Ack struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ack bool `protobuf:"varint,1,opt,name=ack,proto3" json:"ack,omitempty"`
}

func (x *Ack) Reset() {
	*x = Ack{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgqpb_msgq_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_msgqpb_msgq_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_msgqpb_msgq_proto_rawDescGZIP(), []int{3}
}

func (x *Ack) GetAck() bool {
	if x != nil {
		return x.Ack
	}
	return false
}

type CreateQRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Qname string `protobuf:"bytes,1,opt,name=Qname,proto3" json:"Qname,omitempty"`
}

func (x *CreateQRequest) Reset() {
	*x = CreateQRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgqpb_msgq_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateQRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQRequest) ProtoMessage() {}

func (x *CreateQRequest) ProtoReflect() protoreflect.Message {
	mi := &file_msgqpb_msgq_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQRequest.ProtoReflect.Descriptor instead.
func (*CreateQRequest) Descriptor() ([]byte, []int) {
	return file_msgqpb_msgq_proto_rawDescGZIP(), []int{4}
}

func (x *CreateQRequest) GetQname() string {
	if x != nil {
		return x.Qname
	}
	return ""
}

type CreateQResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ack *Ack `protobuf:"bytes,1,opt,name=ack,proto3" json:"ack,omitempty"`
}

func (x *CreateQResponse) Reset() {
	*x = CreateQResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgqpb_msgq_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateQResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQResponse) ProtoMessage() {}

func (x *CreateQResponse) ProtoReflect() protoreflect.Message {
	mi := &file_msgqpb_msgq_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQResponse.ProtoReflect.Descriptor instead.
func (*CreateQResponse) Descriptor() ([]byte, []int) {
	return file_msgqpb_msgq_proto_rawDescGZIP(), []int{5}
}

func (x *CreateQResponse) GetAck() *Ack {
	if x != nil {
		return x.Ack
	}
	return nil
}

type QMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Priority int32  `protobuf:"varint,1,opt,name=priority,proto3" json:"priority,omitempty"`
	Msg      string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *QMessage) Reset() {
	*x = QMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgqpb_msgq_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QMessage) ProtoMessage() {}

func (x *QMessage) ProtoReflect() protoreflect.Message {
	mi := &file_msgqpb_msgq_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QMessage.ProtoReflect.Descriptor instead.
func (*QMessage) Descriptor() ([]byte, []int) {
	return file_msgqpb_msgq_proto_rawDescGZIP(), []int{6}
}

func (x *QMessage) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *QMessage) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type AddMessageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Qname string    `protobuf:"bytes,1,opt,name=Qname,proto3" json:"Qname,omitempty"`
	Qmsg  *QMessage `protobuf:"bytes,2,opt,name=qmsg,proto3" json:"qmsg,omitempty"`
}

func (x *AddMessageRequest) Reset() {
	*x = AddMessageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgqpb_msgq_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMessageRequest) ProtoMessage() {}

func (x *AddMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_msgqpb_msgq_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMessageRequest.ProtoReflect.Descriptor instead.
func (*AddMessageRequest) Descriptor() ([]byte, []int) {
	return file_msgqpb_msgq_proto_rawDescGZIP(), []int{7}
}

func (x *AddMessageRequest) GetQname() string {
	if x != nil {
		return x.Qname
	}
	return ""
}

func (x *AddMessageRequest) GetQmsg() *QMessage {
	if x != nil {
		return x.Qmsg
	}
	return nil
}

type AddMessageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ack *Ack `protobuf:"bytes,1,opt,name=ack,proto3" json:"ack,omitempty"`
}

func (x *AddMessageResponse) Reset() {
	*x = AddMessageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgqpb_msgq_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMessageResponse) ProtoMessage() {}

func (x *AddMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_msgqpb_msgq_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMessageResponse.ProtoReflect.Descriptor instead.
func (*AddMessageResponse) Descriptor() ([]byte, []int) {
	return file_msgqpb_msgq_proto_rawDescGZIP(), []int{8}
}

func (x *AddMessageResponse) GetAck() *Ack {
	if x != nil {
		return x.Ack
	}
	return nil
}

type GetMessageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Qname string `protobuf:"bytes,1,opt,name=Qname,proto3" json:"Qname,omitempty"`
}

func (x *GetMessageRequest) Reset() {
	*x = GetMessageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgqpb_msgq_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageRequest) ProtoMessage() {}

func (x *GetMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_msgqpb_msgq_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageRequest.ProtoReflect.Descriptor instead.
func (*GetMessageRequest) Descriptor() ([]byte, []int) {
	return file_msgqpb_msgq_proto_rawDescGZIP(), []int{9}
}

func (x *GetMessageRequest) GetQname() string {
	if x != nil {
		return x.Qname
	}
	return ""
}

type GetMessageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Qmsg string `protobuf:"bytes,1,opt,name=qmsg,proto3" json:"qmsg,omitempty"`
}

func (x *GetMessageResponse) Reset() {
	*x = GetMessageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgqpb_msgq_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageResponse) ProtoMessage() {}

func (x *GetMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_msgqpb_msgq_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageResponse.ProtoReflect.Descriptor instead.
func (*GetMessageResponse) Descriptor() ([]byte, []int) {
	return file_msgqpb_msgq_proto_rawDescGZIP(), []int{10}
}

func (x *GetMessageResponse) GetQmsg() string {
	if x != nil {
		return x.Qmsg
	}
	return ""
}

type DeleteQRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Qname string `protobuf:"bytes,1,opt,name=Qname,proto3" json:"Qname,omitempty"`
}

func (x *DeleteQRequest) Reset() {
	*x = DeleteQRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgqpb_msgq_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteQRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteQRequest) ProtoMessage() {}

func (x *DeleteQRequest) ProtoReflect() protoreflect.Message {
	mi := &file_msgqpb_msgq_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteQRequest.ProtoReflect.Descriptor instead.
func (*DeleteQRequest) Descriptor() ([]byte, []int) {
	return file_msgqpb_msgq_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteQRequest) GetQname() string {
	if x != nil {
		return x.Qname
	}
	return ""
}

type DeleteQResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ack *Ack `protobuf:"bytes,1,opt,name=ack,proto3" json:"ack,omitempty"`
}

func (x *DeleteQResponse) Reset() {
	*x = DeleteQResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgqpb_msgq_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteQResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteQResponse) ProtoMessage() {}

func (x *DeleteQResponse) ProtoReflect() protoreflect.Message {
	mi := &file_msgqpb_msgq_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteQResponse.ProtoReflect.Descriptor instead.
func (*DeleteQResponse) Descriptor() ([]byte, []int) {
	return file_msgqpb_msgq_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteQResponse) GetAck() *Ack {
	if x != nil {
		return x.Ack
	}
	return nil
}

var File_msgqpb_msgq_proto protoreflect.FileDescriptor

var file_msgqpb_msgq_proto_rawDesc = []byte{
	0x0a, 0x11, 0x6d, 0x73, 0x67, 0x71, 0x70, 0x62, 0x2f, 0x6d, 0x73, 0x67, 0x71, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x73, 0x67, 0x71, 0x22, 0x18, 0x0a, 0x04, 0x50, 0x69, 0x6e,
	0x67, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03,
	0x61, 0x63, 0x6b, 0x22, 0x2d, 0x0a, 0x0b, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1e, 0x0a, 0x04, 0x70, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0a, 0x2e, 0x6d, 0x73, 0x67, 0x71, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x04, 0x70, 0x69,
	0x6e, 0x67, 0x22, 0x2e, 0x0a, 0x0c, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x1e, 0x0a, 0x04, 0x70, 0x6f, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0a, 0x2e, 0x6d, 0x73, 0x67, 0x71, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x04, 0x70, 0x6f,
	0x6e, 0x67, 0x22, 0x17, 0x0a, 0x03, 0x41, 0x63, 0x6b, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x63, 0x6b,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x61, 0x63, 0x6b, 0x22, 0x26, 0x0a, 0x0e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x51, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x51, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x51, 0x6e,
	0x61, 0x6d, 0x65, 0x22, 0x2e, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x51, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x03, 0x61, 0x63, 0x6b, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x6d, 0x73, 0x67, 0x71, 0x2e, 0x41, 0x63, 0x6b, 0x52, 0x03,
	0x61, 0x63, 0x6b, 0x22, 0x38, 0x0a, 0x08, 0x51, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6d,
	0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x4d, 0x0a,
	0x11, 0x41, 0x64, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x51, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x51, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x04, 0x71, 0x6d, 0x73, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6d, 0x73, 0x67, 0x71, 0x2e, 0x51, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x04, 0x71, 0x6d, 0x73, 0x67, 0x22, 0x31, 0x0a, 0x12,
	0x41, 0x64, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x1b, 0x0a, 0x03, 0x61, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x09, 0x2e, 0x6d, 0x73, 0x67, 0x71, 0x2e, 0x41, 0x63, 0x6b, 0x52, 0x03, 0x61, 0x63, 0x6b, 0x22,
	0x29, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x51, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x51, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x28, 0x0a, 0x12, 0x47, 0x65,
	0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x71, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x71, 0x6d, 0x73, 0x67, 0x22, 0x26, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x51, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x51, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x51, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x2e, 0x0a, 0x0f,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x51, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1b, 0x0a, 0x03, 0x61, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x6d,
	0x73, 0x67, 0x71, 0x2e, 0x41, 0x63, 0x6b, 0x52, 0x03, 0x61, 0x63, 0x6b, 0x32, 0xb8, 0x02, 0x0a,
	0x0b, 0x4d, 0x73, 0x67, 0x51, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2f, 0x0a, 0x04,
	0x50, 0x69, 0x6e, 0x67, 0x12, 0x11, 0x2e, 0x6d, 0x73, 0x67, 0x71, 0x2e, 0x50, 0x69, 0x6e, 0x67,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x6d, 0x73, 0x67, 0x71, 0x2e, 0x50,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x38, 0x0a,
	0x07, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x51, 0x12, 0x14, 0x2e, 0x6d, 0x73, 0x67, 0x71, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x51, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15,
	0x2e, 0x6d, 0x73, 0x67, 0x71, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x51, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x0a, 0x41, 0x64, 0x64, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x17, 0x2e, 0x6d, 0x73, 0x67, 0x71, 0x2e, 0x41, 0x64, 0x64,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18,
	0x2e, 0x6d, 0x73, 0x67, 0x71, 0x2e, 0x41, 0x64, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x0a, 0x47, 0x65,
	0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x17, 0x2e, 0x6d, 0x73, 0x67, 0x71, 0x2e,
	0x47, 0x65, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x18, 0x2e, 0x6d, 0x73, 0x67, 0x71, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x38, 0x0a,
	0x07, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x51, 0x12, 0x14, 0x2e, 0x6d, 0x73, 0x67, 0x71, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x51, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15,
	0x2e, 0x6d, 0x73, 0x67, 0x71, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x51, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0d, 0x5a, 0x0b, 0x6d, 0x73, 0x67, 0x71, 0x70,
	0x62, 0x2f, 0x6d, 0x73, 0x67, 0x71, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_msgqpb_msgq_proto_rawDescOnce sync.Once
	file_msgqpb_msgq_proto_rawDescData = file_msgqpb_msgq_proto_rawDesc
)

func file_msgqpb_msgq_proto_rawDescGZIP() []byte {
	file_msgqpb_msgq_proto_rawDescOnce.Do(func() {
		file_msgqpb_msgq_proto_rawDescData = protoimpl.X.CompressGZIP(file_msgqpb_msgq_proto_rawDescData)
	})
	return file_msgqpb_msgq_proto_rawDescData
}

var file_msgqpb_msgq_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_msgqpb_msgq_proto_goTypes = []interface{}{
	(*Ping)(nil),               // 0: msgq.Ping
	(*PingRequest)(nil),        // 1: msgq.PingRequest
	(*PingResponse)(nil),       // 2: msgq.PingResponse
	(*Ack)(nil),                // 3: msgq.Ack
	(*CreateQRequest)(nil),     // 4: msgq.CreateQRequest
	(*CreateQResponse)(nil),    // 5: msgq.CreateQResponse
	(*QMessage)(nil),           // 6: msgq.QMessage
	(*AddMessageRequest)(nil),  // 7: msgq.AddMessageRequest
	(*AddMessageResponse)(nil), // 8: msgq.AddMessageResponse
	(*GetMessageRequest)(nil),  // 9: msgq.GetMessageRequest
	(*GetMessageResponse)(nil), // 10: msgq.GetMessageResponse
	(*DeleteQRequest)(nil),     // 11: msgq.DeleteQRequest
	(*DeleteQResponse)(nil),    // 12: msgq.DeleteQResponse
}
var file_msgqpb_msgq_proto_depIdxs = []int32{
	0,  // 0: msgq.PingRequest.ping:type_name -> msgq.Ping
	0,  // 1: msgq.PingResponse.pong:type_name -> msgq.Ping
	3,  // 2: msgq.CreateQResponse.ack:type_name -> msgq.Ack
	6,  // 3: msgq.AddMessageRequest.qmsg:type_name -> msgq.QMessage
	3,  // 4: msgq.AddMessageResponse.ack:type_name -> msgq.Ack
	3,  // 5: msgq.DeleteQResponse.ack:type_name -> msgq.Ack
	1,  // 6: msgq.MsgQService.Ping:input_type -> msgq.PingRequest
	4,  // 7: msgq.MsgQService.CreateQ:input_type -> msgq.CreateQRequest
	7,  // 8: msgq.MsgQService.AddMessage:input_type -> msgq.AddMessageRequest
	9,  // 9: msgq.MsgQService.GetMessage:input_type -> msgq.GetMessageRequest
	11, // 10: msgq.MsgQService.DeleteQ:input_type -> msgq.DeleteQRequest
	2,  // 11: msgq.MsgQService.Ping:output_type -> msgq.PingResponse
	5,  // 12: msgq.MsgQService.CreateQ:output_type -> msgq.CreateQResponse
	8,  // 13: msgq.MsgQService.AddMessage:output_type -> msgq.AddMessageResponse
	10, // 14: msgq.MsgQService.GetMessage:output_type -> msgq.GetMessageResponse
	12, // 15: msgq.MsgQService.DeleteQ:output_type -> msgq.DeleteQResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_msgqpb_msgq_proto_init() }
func file_msgqpb_msgq_proto_init() {
	if File_msgqpb_msgq_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_msgqpb_msgq_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ping); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgqpb_msgq_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgqpb_msgq_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgqpb_msgq_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ack); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgqpb_msgq_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateQRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgqpb_msgq_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateQResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgqpb_msgq_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgqpb_msgq_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddMessageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgqpb_msgq_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddMessageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgqpb_msgq_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMessageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgqpb_msgq_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMessageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgqpb_msgq_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteQRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgqpb_msgq_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteQResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msgqpb_msgq_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_msgqpb_msgq_proto_goTypes,
		DependencyIndexes: file_msgqpb_msgq_proto_depIdxs,
		MessageInfos:      file_msgqpb_msgq_proto_msgTypes,
	}.Build()
	File_msgqpb_msgq_proto = out.File
	file_msgqpb_msgq_proto_rawDesc = nil
	file_msgqpb_msgq_proto_goTypes = nil
	file_msgqpb_msgq_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MsgQServiceClient is the client API for MsgQService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgQServiceClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	CreateQ(ctx context.Context, in *CreateQRequest, opts ...grpc.CallOption) (*CreateQResponse, error)
	AddMessage(ctx context.Context, in *AddMessageRequest, opts ...grpc.CallOption) (*AddMessageResponse, error)
	GetMessage(ctx context.Context, in *GetMessageRequest, opts ...grpc.CallOption) (*GetMessageResponse, error)
	DeleteQ(ctx context.Context, in *DeleteQRequest, opts ...grpc.CallOption) (*DeleteQResponse, error)
}

type msgQServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgQServiceClient(cc grpc.ClientConnInterface) MsgQServiceClient {
	return &msgQServiceClient{cc}
}

func (c *msgQServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, "/msgq.MsgQService/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgQServiceClient) CreateQ(ctx context.Context, in *CreateQRequest, opts ...grpc.CallOption) (*CreateQResponse, error) {
	out := new(CreateQResponse)
	err := c.cc.Invoke(ctx, "/msgq.MsgQService/CreateQ", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgQServiceClient) AddMessage(ctx context.Context, in *AddMessageRequest, opts ...grpc.CallOption) (*AddMessageResponse, error) {
	out := new(AddMessageResponse)
	err := c.cc.Invoke(ctx, "/msgq.MsgQService/AddMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgQServiceClient) GetMessage(ctx context.Context, in *GetMessageRequest, opts ...grpc.CallOption) (*GetMessageResponse, error) {
	out := new(GetMessageResponse)
	err := c.cc.Invoke(ctx, "/msgq.MsgQService/GetMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgQServiceClient) DeleteQ(ctx context.Context, in *DeleteQRequest, opts ...grpc.CallOption) (*DeleteQResponse, error) {
	out := new(DeleteQResponse)
	err := c.cc.Invoke(ctx, "/msgq.MsgQService/DeleteQ", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgQServiceServer is the server API for MsgQService service.
type MsgQServiceServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	CreateQ(context.Context, *CreateQRequest) (*CreateQResponse, error)
	AddMessage(context.Context, *AddMessageRequest) (*AddMessageResponse, error)
	GetMessage(context.Context, *GetMessageRequest) (*GetMessageResponse, error)
	DeleteQ(context.Context, *DeleteQRequest) (*DeleteQResponse, error)
}

// UnimplementedMsgQServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMsgQServiceServer struct {
}

func (*UnimplementedMsgQServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (*UnimplementedMsgQServiceServer) CreateQ(context.Context, *CreateQRequest) (*CreateQResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateQ not implemented")
}
func (*UnimplementedMsgQServiceServer) AddMessage(context.Context, *AddMessageRequest) (*AddMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddMessage not implemented")
}
func (*UnimplementedMsgQServiceServer) GetMessage(context.Context, *GetMessageRequest) (*GetMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMessage not implemented")
}
func (*UnimplementedMsgQServiceServer) DeleteQ(context.Context, *DeleteQRequest) (*DeleteQResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteQ not implemented")
}

func RegisterMsgQServiceServer(s *grpc.Server, srv MsgQServiceServer) {
	s.RegisterService(&_MsgQService_serviceDesc, srv)
}

func _MsgQService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgQServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/msgq.MsgQService/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgQServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgQService_CreateQ_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateQRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgQServiceServer).CreateQ(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/msgq.MsgQService/CreateQ",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgQServiceServer).CreateQ(ctx, req.(*CreateQRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgQService_AddMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgQServiceServer).AddMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/msgq.MsgQService/AddMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgQServiceServer).AddMessage(ctx, req.(*AddMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgQService_GetMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgQServiceServer).GetMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/msgq.MsgQService/GetMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgQServiceServer).GetMessage(ctx, req.(*GetMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgQService_DeleteQ_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteQRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgQServiceServer).DeleteQ(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/msgq.MsgQService/DeleteQ",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgQServiceServer).DeleteQ(ctx, req.(*DeleteQRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MsgQService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "msgq.MsgQService",
	HandlerType: (*MsgQServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _MsgQService_Ping_Handler,
		},
		{
			MethodName: "CreateQ",
			Handler:    _MsgQService_CreateQ_Handler,
		},
		{
			MethodName: "AddMessage",
			Handler:    _MsgQService_AddMessage_Handler,
		},
		{
			MethodName: "GetMessage",
			Handler:    _MsgQService_GetMessage_Handler,
		},
		{
			MethodName: "DeleteQ",
			Handler:    _MsgQService_DeleteQ_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "msgqpb/msgq.proto",
}
